// 389. Find the Difference

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
*/

const findTheDifference = function (s, t) {
  const first = s.split("");
  const randomm = t.split("");

  let x = 0;
  while (x < first.length) {
    for (let i = 0; i < first.length; i++) {
      for (let j = 0; j < randomm.length; j++) {
        if (first[i] === randomm[j]) {
          first.splice(i, 1);
          randomm.splice(j, 1);
        }
      }
    }
  }
  return randomm[0];
};

console.log(findTheDifference("abcd", "abcde"));
console.log(findTheDifference("", "y"));
console.log(findTheDifference("a", "aa"));
console.log(findTheDifference("sddmfrddd", "sddmfrddd4"));

const differrrrr = function (s, t) {
  let result = 0;

  for (let char of s) {
    result ^= char.charCodeAt(0);
  }
  for (let char of t) {
    result ^= char.charCodeAt(0);
  }
  return String.fromCharCode(result);
};
console.log(differrrrr("abcd", "abcde"));
console.log(differrrrr("", "y"));
console.log(differrrrr("a", "aa"));
console.log(differrrrr("sddmfrddd", "sddmfrddd4"));
